# Generated by Django 5.1.3 on 2024-11-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivaldetails',
            name='any_extra_details',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='departuredetails',
            name='any_extra_details',
        ),
    ]
