# Generated by Django 5.1.2 on 2024-11-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
