# Generated by Django 5.1.3 on 2024-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_arrivaldetails_any_extra_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='fare',
        ),
        migrations.AddField(
            model_name='bookings',
            name='name_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
