# Generated by Django 5.1.3 on 2024-11-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bookings_fare_bookings_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='source_of_funding',
        ),
    ]
