# Generated by Django 5.1.2 on 2024-11-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_arrivaldetails_date_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS log_bookings (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                booking_id INTEGER,
                name_user TEXT,
                type_of_booking TEXT,
                status TEXT,
                details TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TRIGGER after_booking_insert
            AFTER INSERT ON api_bookings
            BEGIN
                INSERT INTO log_bookings (booking_id, name_user, type_of_booking, status, details)
                VALUES (NEW.booking_id, NEW.name_user, NEW.type_of_booking, NEW.status, NEW.any_specific_details);
            END;

            CREATE TABLE IF NOT EXISTS log_auth_users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                username TEXT,
                email TEXT,
                user_type TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TRIGGER after_user_signup
            AFTER INSERT ON api_user
            BEGIN
                INSERT INTO log_auth_users (user_id, username, email, user_type)
                VALUES (NEW.id, NEW.username, NEW.email_id, NEW.user_type);
            END;
            """
        )
    ]