# Generated by Django 5.1.3 on 2024-11-10 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_bookings_source_of_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivaldetails',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departuredetails',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
    ]
