# Generated by Django 5.1.3 on 2024-11-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_arrivaldetails_vehicle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='admin_id',
        ),
    ]
