# Generated by Django 5.1.3 on 2024-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_notifications_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departuredetails',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='departuredetails',
            name='drop_off_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='departuredetails',
            name='pickup_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='departuredetails',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='departuredetails',
            name='type_of_vehicle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
